# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: base.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'base.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbase.proto\x12\x0f\x61tividade5.base\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x01\n\x18\x43reateReservationRequest\x12\x31\n\rcheck_in_date\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x37\n\x0e\x63heck_out_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x88\x01\x01\x12\x0e\n\x06origin\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x04 \x01(\t\x12\x18\n\x10number_of_people\x18\x05 \x01(\x05\x42\x11\n\x0f_check_out_date\"m\n\x19\x43reateReservationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1b\n\x0ereservation_id\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x11\n\x0f_reservation_id\".\n\x14RevertBookingRequest\x12\x16\n\x0ereservation_id\x18\x01 \x01(\t\"9\n\x15RevertBookingResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'base_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATERESERVATIONREQUEST']._serialized_start=65
  _globals['_CREATERESERVATIONREQUEST']._serialized_end=281
  _globals['_CREATERESERVATIONRESPONSE']._serialized_start=283
  _globals['_CREATERESERVATIONRESPONSE']._serialized_end=392
  _globals['_REVERTBOOKINGREQUEST']._serialized_start=394
  _globals['_REVERTBOOKINGREQUEST']._serialized_end=440
  _globals['_REVERTBOOKINGRESPONSE']._serialized_start=442
  _globals['_REVERTBOOKINGRESPONSE']._serialized_end=499
# @@protoc_insertion_point(module_scope)
