// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Reservation struct {
	ID        string
	RoomID    string
	StartDate time.Time
	EndDate   sql.NullTime
}

type Room struct {
	ID        string
	Name      string
	Location  string
	MaxPeople int64
	Price     int64
}
