# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hotel-chain.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'hotel-chain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_pb2 as base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11hotel-chain.proto\x12\x15\x61tividade5.hotelchain\x1a\nbase.proto2\xd6\x01\n\x0cHotelService\x12\x64\n\tBookHotel\x12).atividade5.base.CreateReservationRequest\x1a*.atividade5.base.CreateReservationResponse\"\x00\x12`\n\rRevertBooking\x12%.atividade5.base.RevertBookingRequest\x1a&.atividade5.base.RevertBookingResponse\"\x00\x42\x14Z\x12protos/hotel-chainb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hotel_chain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022protos/hotel-chain'
  _globals['_HOTELSERVICE']._serialized_start=57
  _globals['_HOTELSERVICE']._serialized_end=271
# @@protoc_insertion_point(module_scope)
