// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.2
// source: base.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReservationRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CheckInDate    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=check_in_date,json=checkInDate,proto3"`
	xxx_hidden_CheckOutDate   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=check_out_date,json=checkOutDate,proto3,oneof"`
	xxx_hidden_Origin         string                 `protobuf:"bytes,3,opt,name=origin,proto3"`
	xxx_hidden_Destination    string                 `protobuf:"bytes,4,opt,name=destination,proto3"`
	xxx_hidden_NumberOfPeople int32                  `protobuf:"varint,5,opt,name=number_of_people,json=numberOfPeople,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CreateReservationRequest) Reset() {
	*x = CreateReservationRequest{}
	mi := &file_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationRequest) ProtoMessage() {}

func (x *CreateReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateReservationRequest) GetCheckInDate() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CheckInDate
	}
	return nil
}

func (x *CreateReservationRequest) GetCheckOutDate() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CheckOutDate
	}
	return nil
}

func (x *CreateReservationRequest) GetOrigin() string {
	if x != nil {
		return x.xxx_hidden_Origin
	}
	return ""
}

func (x *CreateReservationRequest) GetDestination() string {
	if x != nil {
		return x.xxx_hidden_Destination
	}
	return ""
}

func (x *CreateReservationRequest) GetNumberOfPeople() int32 {
	if x != nil {
		return x.xxx_hidden_NumberOfPeople
	}
	return 0
}

func (x *CreateReservationRequest) SetCheckInDate(v *timestamppb.Timestamp) {
	x.xxx_hidden_CheckInDate = v
}

func (x *CreateReservationRequest) SetCheckOutDate(v *timestamppb.Timestamp) {
	x.xxx_hidden_CheckOutDate = v
}

func (x *CreateReservationRequest) SetOrigin(v string) {
	x.xxx_hidden_Origin = v
}

func (x *CreateReservationRequest) SetDestination(v string) {
	x.xxx_hidden_Destination = v
}

func (x *CreateReservationRequest) SetNumberOfPeople(v int32) {
	x.xxx_hidden_NumberOfPeople = v
}

func (x *CreateReservationRequest) HasCheckInDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CheckInDate != nil
}

func (x *CreateReservationRequest) HasCheckOutDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CheckOutDate != nil
}

func (x *CreateReservationRequest) ClearCheckInDate() {
	x.xxx_hidden_CheckInDate = nil
}

func (x *CreateReservationRequest) ClearCheckOutDate() {
	x.xxx_hidden_CheckOutDate = nil
}

type CreateReservationRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Required check-in date
	CheckInDate *timestamppb.Timestamp
	// Optional check-out date
	CheckOutDate *timestamppb.Timestamp
	// Required origin
	Origin string
	// Required destination
	Destination string
	// Required number of people
	NumberOfPeople int32
}

func (b0 CreateReservationRequest_builder) Build() *CreateReservationRequest {
	m0 := &CreateReservationRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_CheckInDate = b.CheckInDate
	x.xxx_hidden_CheckOutDate = b.CheckOutDate
	x.xxx_hidden_Origin = b.Origin
	x.xxx_hidden_Destination = b.Destination
	x.xxx_hidden_NumberOfPeople = b.NumberOfPeople
	return m0
}

type CreateReservationResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Success       bool                   `protobuf:"varint,1,opt,name=success,proto3"`
	xxx_hidden_Message       string                 `protobuf:"bytes,2,opt,name=message,proto3"`
	xxx_hidden_ReservationId string                 `protobuf:"bytes,3,opt,name=reservation_id,json=reservationId,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CreateReservationResponse) Reset() {
	*x = CreateReservationResponse{}
	mi := &file_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationResponse) ProtoMessage() {}

func (x *CreateReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateReservationResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *CreateReservationResponse) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *CreateReservationResponse) GetReservationId() string {
	if x != nil {
		return x.xxx_hidden_ReservationId
	}
	return ""
}

func (x *CreateReservationResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
}

func (x *CreateReservationResponse) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

func (x *CreateReservationResponse) SetReservationId(v string) {
	x.xxx_hidden_ReservationId = v
}

type CreateReservationResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Success       bool
	Message       string
	ReservationId string
}

func (b0 CreateReservationResponse_builder) Build() *CreateReservationResponse {
	m0 := &CreateReservationResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Success = b.Success
	x.xxx_hidden_Message = b.Message
	x.xxx_hidden_ReservationId = b.ReservationId
	return m0
}

type RevertBookingRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RevertBookingRequest) Reset() {
	*x = RevertBookingRequest{}
	mi := &file_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevertBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertBookingRequest) ProtoMessage() {}

func (x *RevertBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RevertBookingRequest) GetReservationId() string {
	if x != nil {
		return x.xxx_hidden_ReservationId
	}
	return ""
}

func (x *RevertBookingRequest) SetReservationId(v string) {
	x.xxx_hidden_ReservationId = v
}

type RevertBookingRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ReservationId string
}

func (b0 RevertBookingRequest_builder) Build() *RevertBookingRequest {
	m0 := &RevertBookingRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ReservationId = b.ReservationId
	return m0
}

type RevertBookingResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Success bool                   `protobuf:"varint,1,opt,name=success,proto3"`
	xxx_hidden_Message string                 `protobuf:"bytes,2,opt,name=message,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RevertBookingResponse) Reset() {
	*x = RevertBookingResponse{}
	mi := &file_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevertBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertBookingResponse) ProtoMessage() {}

func (x *RevertBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RevertBookingResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *RevertBookingResponse) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *RevertBookingResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
}

func (x *RevertBookingResponse) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

type RevertBookingResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Success bool
	Message string
}

func (b0 RevertBookingResponse_builder) Build() *RevertBookingResponse {
	m0 := &RevertBookingResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Success = b.Success
	x.xxx_hidden_Message = b.Message
	return m0
}

var File_base_proto protoreflect.FileDescriptor

var file_base_proto_rawDesc = string([]byte{
	0x0a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x74,
	0x69, 0x76, 0x69, 0x64, 0x61, 0x64, 0x65, 0x35, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x98,
	0x02, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x0d, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x5f, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x45, 0x0a, 0x0e, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x5f, 0x6f, 0x75, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48,
	0x00, 0x52, 0x0c, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x44, 0x61, 0x74, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x10,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6f, 0x66, 0x5f, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66,
	0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x5f, 0x6f, 0x75, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x22, 0x76, 0x0a, 0x19, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x22, 0x3d, 0x0a, 0x14, 0x52, 0x65, 0x76, 0x65, 0x72, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x22, 0x4b, 0x0a, 0x15, 0x52, 0x65, 0x76, 0x65, 0x72, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x2a, 0x5a,
	0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x69, 0x68,
	0x78, 0x6d, 0x2f, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x2d, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var file_base_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_base_proto_goTypes = []any{
	(*CreateReservationRequest)(nil),  // 0: atividade5.base.CreateReservationRequest
	(*CreateReservationResponse)(nil), // 1: atividade5.base.CreateReservationResponse
	(*RevertBookingRequest)(nil),      // 2: atividade5.base.RevertBookingRequest
	(*RevertBookingResponse)(nil),     // 3: atividade5.base.RevertBookingResponse
	(*timestamppb.Timestamp)(nil),     // 4: google.protobuf.Timestamp
}
var file_base_proto_depIdxs = []int32{
	4, // 0: atividade5.base.CreateReservationRequest.check_in_date:type_name -> google.protobuf.Timestamp
	4, // 1: atividade5.base.CreateReservationRequest.check_out_date:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_base_proto_init() }
func file_base_proto_init() {
	if File_base_proto != nil {
		return
	}
	file_base_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_proto_rawDesc), len(file_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_proto_goTypes,
		DependencyIndexes: file_base_proto_depIdxs,
		MessageInfos:      file_base_proto_msgTypes,
	}.Build()
	File_base_proto = out.File
	file_base_proto_goTypes = nil
	file_base_proto_depIdxs = nil
}
