// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: car-rental/proto/car-rental/car-rental.proto

package car_rental

import (
	context "context"
	base "github.com/thihxm/car-rental/proto/base"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CarRentalService_RentCar_FullMethodName = "/atividade5.carrental.CarRentalService/RentCar"
)

// CarRentalServiceClient is the client API for CarRentalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CarRentalServiceClient interface {
	RentCar(ctx context.Context, in *base.CreateReservationRequest, opts ...grpc.CallOption) (*base.CreateReservationResponse, error)
}

type carRentalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCarRentalServiceClient(cc grpc.ClientConnInterface) CarRentalServiceClient {
	return &carRentalServiceClient{cc}
}

func (c *carRentalServiceClient) RentCar(ctx context.Context, in *base.CreateReservationRequest, opts ...grpc.CallOption) (*base.CreateReservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(base.CreateReservationResponse)
	err := c.cc.Invoke(ctx, CarRentalService_RentCar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarRentalServiceServer is the server API for CarRentalService service.
// All implementations must embed UnimplementedCarRentalServiceServer
// for forward compatibility.
type CarRentalServiceServer interface {
	RentCar(context.Context, *base.CreateReservationRequest) (*base.CreateReservationResponse, error)
	mustEmbedUnimplementedCarRentalServiceServer()
}

// UnimplementedCarRentalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCarRentalServiceServer struct{}

func (UnimplementedCarRentalServiceServer) RentCar(context.Context, *base.CreateReservationRequest) (*base.CreateReservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RentCar not implemented")
}
func (UnimplementedCarRentalServiceServer) mustEmbedUnimplementedCarRentalServiceServer() {}
func (UnimplementedCarRentalServiceServer) testEmbeddedByValue()                          {}

// UnsafeCarRentalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CarRentalServiceServer will
// result in compilation errors.
type UnsafeCarRentalServiceServer interface {
	mustEmbedUnimplementedCarRentalServiceServer()
}

func RegisterCarRentalServiceServer(s grpc.ServiceRegistrar, srv CarRentalServiceServer) {
	// If the following call pancis, it indicates UnimplementedCarRentalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CarRentalService_ServiceDesc, srv)
}

func _CarRentalService_RentCar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(base.CreateReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarRentalServiceServer).RentCar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CarRentalService_RentCar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarRentalServiceServer).RentCar(ctx, req.(*base.CreateReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CarRentalService_ServiceDesc is the grpc.ServiceDesc for CarRentalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CarRentalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atividade5.carrental.CarRentalService",
	HandlerType: (*CarRentalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RentCar",
			Handler:    _CarRentalService_RentCar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "car-rental/proto/car-rental/car-rental.proto",
}
