// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Car struct {
	ID       string
	Brand    string
	Model    string
	Seats    int64
	Price    int64
	Location string
}

type Reservation struct {
	ID        string
	CarID     string
	StartDate time.Time
	EndDate   sql.NullTime
}
